version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: 'orats'
      POSTGRES_PASSWORD: 'yourpassword'
    # ports:
    #   - '5432:5432'
    expose:
      - '5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    restart: 'always'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass yourpassword
    hostname: 'redis-db'
    # ports:
    #   - '6379:6379'
    expose:
      - '6379'
    volumes:
      - 'redis:/var/lib/redis/data'
    restart: 'always'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    hostname: 'rails_app'
    expose:
       - '3000'
#    ports:
#      - '3000:3000'
    volumes:
      - '.:/orats'
      - 'assets-volume:/orats/public'
    env_file:
      - '.env'
    restart: 'always'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/orats'
    env_file:
      - '.env'
    restart: 'always'

  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    # ports:
    #   - '28080:28080'
    expose:
      - '28080'
    volumes:
      - '.:/orats'
    env_file:
      - '.env'
    restart: 'always'

  nginx:
    depends_on:
      - 'website'
    image: 'nginx'
    command: /bin/bash -c "cat < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
      - 'assets-volume:/var/www/orats/public'
      - '.:/var/www/orats'
    ports:
      - "80:80"
    restart: 'always'


volumes:
  redis:
  postgres:
  assets-volume:
