---

development:
  url: <%= ENV['DATABASE_URL'].to_s.gsub('?', '_development?') %>

test:
  url: <%= ENV['DATABASE_URL'].to_s.gsub('?', '_test?') %>

staging:
  url: <%= ENV['DATABASE_URL'].to_s.gsub('?', '_staging?') %>

production:
  url: <%= ENV['DATABASE_URL'].to_s.gsub('?', '_production?') %>
